import {
    Report,
    ReportAction,
    User,
    DashboardStats,
    AuditLogEntry,
    AccessPermission,
    OfficerAssignment,
    KecamatanData,
    IncidentReport,
} from "./types";

export const mockUsers: User[] = [
    {
        id: "u1",
        name: "Dr. Rina Wahyuni",
        role: "PSIKOLOG",
        email: "rina@sisaka.id",
        phone: "08123456789",
        location: "Bontang Selatan",
    },
    {
        id: "u2",
        name: "Ahmad Fadli",
        role: "ADMIN",
        email: "ahmad@sisaka.id",
        phone: "08129876543",
        location: "Bontang Utara",
    },
    {
        id: "u3",
        name: "Siti Nurhaliza",
        role: "PSIKOLOG",
        email: "siti@sisaka.id",
        phone: "08131112222",
        location: "Bontang Barat",
    },
    {
        id: "u4",
        name: "Budi Prasetyo",
        role: "PETUGAS",
        email: "budi@sisaka.id",
        phone: "08134445556",
        location: "Bontang Selatan",
    },
    {
        id: "u5",
        name: "Dewi Anggraini",
        role: "PETUGAS",
        email: "dewi@sisaka.id",
        phone: "08137778889",
        location: "Bontang Utara",
    },
];

// Bontang coordinates: lat ~0.1, lng ~117.5
export const mockReports: Report[] = [
    {
        id: "RPT-001",
        victimName: "Sari Andini",
        maskedName: "S*** A*****",
        reportType: "PANIC_BUTTON",
        violenceCategory: "Fisik",
        description: "",
        latitude: 0.1253,
        longitude: 117.4747,
        kecamatan: "Bontang Selatan",
        kelurahan: "Berbas Pantai",
        status: "NEW",
        assignedTo: "u4",
        createdAt: "2026-03-07T14:30:00Z",
    },
    {
        id: "RPT-002",
        victimName: "Maya Putri",
        maskedName: "M*** P****",
        reportType: "FORM",
        violenceCategory: "Psikis, Seksual",
        description:
            "Kejadian berlangsung di rumah pada malam hari. Pelaku adalah anggota keluarga dekat. Korban mengalami trauma psikis berat dan memerlukan pendampingan segera.",
        latitude: 0.1365,
        longitude: 117.4921,
        kecamatan: "Bontang Selatan",
        kelurahan: "Tanjung Laut",
        status: "RESPONDING",
        assignedTo: "u1",
        createdAt: "2026-03-06T09:15:00Z",
    },
    {
        id: "RPT-003",
        victimName: "Dewi Lestari",
        maskedName: "D*** L******",
        reportType: "FORM",
        violenceCategory: "Fisik, Psikis",
        description:
            "Korban melaporkan adanya kekerasan fisik berulang dari pasangan. Sudah berlangsung selama 2 tahun. Korban membutuhkan tempat perlindungan sementara.",
        latitude: 0.1521,
        longitude: 117.4583,
        kecamatan: "Bontang Utara",
        kelurahan: "Bontang Kuala",
        status: "CONTACTED",
        assignedTo: "u3",
        createdAt: "2026-03-05T16:45:00Z",
    },
    {
        id: "RPT-004",
        victimName: "Anisa Rahmawati",
        maskedName: "A**** R*********",
        reportType: "PANIC_BUTTON",
        violenceCategory: "Fisik",
        description: "",
        latitude: 0.1088,
        longitude: 117.4392,
        kecamatan: "Bontang Barat",
        kelurahan: "Kanaan",
        status: "ARCHIVED",
        assignedTo: "u4",
        createdAt: "2026-03-04T21:00:00Z",
    },
    {
        id: "RPT-005",
        victimName: "Linda Kusuma",
        maskedName: "L**** K*****",
        reportType: "FORM",
        violenceCategory: "Seksual",
        description:
            "Kejadian terjadi di tempat kerja. Pelaku adalah rekan kerja. Korban meminta kerahasiaan identitas secara penuh.",
        latitude: 0.1682,
        longitude: 117.4835,
        kecamatan: "Bontang Utara",
        kelurahan: "Guntung",
        status: "NEW",
        assignedTo: "u5",
        createdAt: "2026-03-07T08:20:00Z",
    },
    {
        id: "RPT-006",
        victimName: "Putri Ayu",
        maskedName: "P**** A**",
        reportType: "FORM",
        violenceCategory: "Psikis",
        description:
            "Korban mengalami intimidasi dan ancaman verbal secara berulang dari mantan pasangan.",
        latitude: 0.1197,
        longitude: 117.4501,
        kecamatan: "Bontang Barat",
        kelurahan: "Belimbing",
        status: "NEW",
        assignedTo: "u1",
        createdAt: "2026-03-07T11:30:00Z",
    },
    {
        id: "RPT-007",
        victimName: "Rani Safitri",
        maskedName: "R*** S******",
        reportType: "FORM",
        violenceCategory: "Fisik",
        description: "Kekerasan oleh suami di rumah. Luka memar pada wajah dan lengan.",
        latitude: 0.1315,
        longitude: 117.4669,
        kecamatan: "Bontang Selatan",
        kelurahan: "Berbas Tengah",
        status: "RESPONDING",
        assignedTo: "u4",
        createdAt: "2026-03-06T20:10:00Z",
    },
    {
        id: "RPT-008",
        victimName: "Nur Hidayah",
        maskedName: "N** H******",
        reportType: "PANIC_BUTTON",
        violenceCategory: "Fisik",
        description: "",
        latitude: 0.1452,
        longitude: 117.4713,
        kecamatan: "Bontang Utara",
        kelurahan: "Api-Api",
        status: "NEW",
        createdAt: "2026-03-07T15:05:00Z",
    },
];

export const mockActions: ReportAction[] = [
    {
        id: "act-001",
        reportId: "RPT-002",
        userId: "u1",
        userName: "Dr. Rina Wahyuni",
        actionTaken: "HUBUNGI_KORBAN",
        timestamp: "2026-03-06T10:00:00Z",
    },
    {
        id: "act-002",
        reportId: "RPT-002",
        userId: "u2",
        userName: "Ahmad Fadli",
        actionTaken: "KIRIM_PETUGAS",
        timestamp: "2026-03-06T10:15:00Z",
    },
    {
        id: "act-003",
        reportId: "RPT-003",
        userId: "u3",
        userName: "Siti Nurhaliza",
        actionTaken: "HUBUNGI_KORBAN",
        timestamp: "2026-03-05T17:30:00Z",
    },
    {
        id: "act-004",
        reportId: "RPT-004",
        userId: "u2",
        userName: "Ahmad Fadli",
        actionTaken: "ARSIPKAN",
        timestamp: "2026-03-05T09:00:00Z",
    },
    {
        id: "act-005",
        reportId: "RPT-007",
        userId: "u4",
        userName: "Budi Prasetyo",
        actionTaken: "KIRIM_PETUGAS",
        timestamp: "2026-03-06T21:00:00Z",
    },
];

export const mockDashboardStats: DashboardStats = {
    totalReports: mockReports.length,
    newReports: mockReports.filter((r) => r.status === "NEW").length,
    respondingReports: mockReports.filter(
        (r) => r.status === "RESPONDING" || r.status === "CONTACTED"
    ).length,
    archivedReports: mockReports.filter((r) => r.status === "ARCHIVED").length,
};

// --- Phase 3 Mock Data ---

export const mockAuditLog: AuditLogEntry[] = [
    {
        id: "log-001",
        userId: "u1",
        userName: "Dr. Rina Wahyuni",
        userRole: "PSIKOLOG",
        action: "VIEW_DETAIL",
        reportId: "RPT-002",
        reportMaskedName: "M*** P****",
        timestamp: "2026-03-07T14:02:00Z",
        ipAddress: "192.168.1.10",
    },
    {
        id: "log-002",
        userId: "u2",
        userName: "Ahmad Fadli",
        userRole: "ADMIN",
        action: "VIEW_IDENTITY",
        reportId: "RPT-001",
        reportMaskedName: "S*** A*****",
        timestamp: "2026-03-07T13:45:00Z",
        ipAddress: "192.168.1.20",
    },
    {
        id: "log-003",
        userId: "u4",
        userName: "Budi Prasetyo",
        userRole: "PETUGAS",
        action: "UPDATE_STATUS",
        reportId: "RPT-007",
        reportMaskedName: "R*** S******",
        timestamp: "2026-03-07T12:30:00Z",
        ipAddress: "10.0.0.5",
    },
    {
        id: "log-004",
        userId: "u2",
        userName: "Ahmad Fadli",
        userRole: "ADMIN",
        action: "ASSIGN_OFFICER",
        reportId: "RPT-005",
        reportMaskedName: "L**** K*****",
        timestamp: "2026-03-07T11:00:00Z",
        ipAddress: "192.168.1.20",
    },
    {
        id: "log-005",
        userId: "u3",
        userName: "Siti Nurhaliza",
        userRole: "PSIKOLOG",
        action: "VIEW_DETAIL",
        reportId: "RPT-003",
        reportMaskedName: "D*** L******",
        timestamp: "2026-03-07T10:15:00Z",
        ipAddress: "192.168.1.15",
    },
    {
        id: "log-006",
        userId: "u1",
        userName: "Dr. Rina Wahyuni",
        userRole: "PSIKOLOG",
        action: "EXPORT_DATA",
        reportId: "RPT-002",
        reportMaskedName: "M*** P****",
        timestamp: "2026-03-07T09:20:00Z",
        ipAddress: "192.168.1.10",
    },
    {
        id: "log-007",
        userId: "u5",
        userName: "Dewi Anggraini",
        userRole: "PETUGAS",
        action: "VIEW_DETAIL",
        reportId: "RPT-005",
        reportMaskedName: "L**** K*****",
        timestamp: "2026-03-07T08:45:00Z",
        ipAddress: "10.0.0.8",
    },
    {
        id: "log-008",
        userId: "u2",
        userName: "Ahmad Fadli",
        userRole: "ADMIN",
        action: "EDIT_REPORT",
        reportId: "RPT-004",
        reportMaskedName: "A**** R*********",
        timestamp: "2026-03-06T16:30:00Z",
        ipAddress: "192.168.1.20",
    },
    {
        id: "log-009",
        userId: "u4",
        userName: "Budi Prasetyo",
        userRole: "PETUGAS",
        action: "VIEW_IDENTITY",
        reportId: "RPT-001",
        reportMaskedName: "S*** A*****",
        timestamp: "2026-03-06T15:00:00Z",
        ipAddress: "10.0.0.5",
    },
    {
        id: "log-010",
        userId: "u1",
        userName: "Dr. Rina Wahyuni",
        userRole: "PSIKOLOG",
        action: "VIEW_DETAIL",
        reportId: "RPT-006",
        reportMaskedName: "P**** A**",
        timestamp: "2026-03-06T14:10:00Z",
        ipAddress: "192.168.1.10",
    },
];

export const mockAccessPermissions: AccessPermission[] = [
    {
        userId: "u1",
        userName: "Dr. Rina Wahyuni",
        userRole: "PSIKOLOG",
        canViewData: true,
        canEditData: true,
        canExportData: true,
    },
    {
        userId: "u2",
        userName: "Ahmad Fadli",
        userRole: "ADMIN",
        canViewData: true,
        canEditData: true,
        canExportData: true,
    },
    {
        userId: "u3",
        userName: "Siti Nurhaliza",
        userRole: "PSIKOLOG",
        canViewData: true,
        canEditData: false,
        canExportData: false,
    },
    {
        userId: "u4",
        userName: "Budi Prasetyo",
        userRole: "PETUGAS",
        canViewData: true,
        canEditData: false,
        canExportData: false,
    },
    {
        userId: "u5",
        userName: "Dewi Anggraini",
        userRole: "PETUGAS",
        canViewData: true,
        canEditData: false,
        canExportData: false,
    },
];

export const mockOfficerAssignments: OfficerAssignment[] = [
    { officerId: "u4", reportId: "RPT-001", assignedAt: "2026-03-07T14:35:00Z", status: "ACTIVE" },
    { officerId: "u1", reportId: "RPT-002", assignedAt: "2026-03-06T09:20:00Z", status: "ACTIVE" },
    { officerId: "u3", reportId: "RPT-003", assignedAt: "2026-03-05T17:00:00Z", status: "ACTIVE" },
    { officerId: "u4", reportId: "RPT-004", assignedAt: "2026-03-04T21:05:00Z", status: "COMPLETED", completedAt: "2026-03-05T09:00:00Z" },
    { officerId: "u5", reportId: "RPT-005", assignedAt: "2026-03-07T08:25:00Z", status: "ACTIVE" },
    { officerId: "u1", reportId: "RPT-006", assignedAt: "2026-03-07T11:35:00Z", status: "ACTIVE" },
    { officerId: "u4", reportId: "RPT-007", assignedAt: "2026-03-06T20:15:00Z", status: "ACTIVE" },
];

export const mockBontangData: KecamatanData[] = [
    {
        name: "Bontang Selatan",
        caseCount: 3,
        kelurahan: [
            { name: "Berbas Pantai", caseCount: 1 },
            { name: "Tanjung Laut", caseCount: 1 },
            { name: "Berbas Tengah", caseCount: 1 },
            { name: "Tanjung Laut Indah", caseCount: 0 },
            { name: "Satimpo", caseCount: 0 },
            { name: "Bontang Lestari", caseCount: 0 },
        ],
    },
    {
        name: "Bontang Utara",
        caseCount: 3,
        kelurahan: [
            { name: "Bontang Kuala", caseCount: 1 },
            { name: "Guntung", caseCount: 1 },
            { name: "Api-Api", caseCount: 1 },
            { name: "Lok Tuan", caseCount: 0 },
            { name: "Bontang Baru", caseCount: 0 },
            { name: "Gunung Elai", caseCount: 0 },
        ],
    },
    {
        name: "Bontang Barat",
        caseCount: 2,
        kelurahan: [
            { name: "Kanaan", caseCount: 1 },
            { name: "Belimbing", caseCount: 1 },
            { name: "Gunung Telihan", caseCount: 0 },
        ],
    },
];

// ── Mock Incident Reports (filled by officers) ──────────────────────
export const mockIncidentReports: IncidentReport[] = [
    {
        id: "INC-001",
        reportId: "RPT-001",
        officerId: "u4",
        officerName: "Budi Prasetyo",
        kronologi:
            "Pada tanggal tersebut, petugas menerima laporan melalui sistem Si SAKA dan segera menuju lokasi kejadian untuk melakukan asesmen awal. Setelah tiba di lokasi, petugas menemukan korban dalam kondisi trauma.",
        tindakan:
            "1. Melakukan asesmen kondisi korban\n2. Menghubungi psikolog untuk konseling awal\n3. Mengarahkan korban ke tempat perlindungan sementara",
        rekomendasi:
            "Diperlukan pendampingan psikologis lanjutan dan pemantauan berkala selama 2 minggu ke depan.",
        photos: [
            {
                id: "ph-001",
                category: "LOKASI",
                fileName: "foto_lokasi_rpt001.jpg",
                url: "/placeholder-lokasi.jpg",
            },
            {
                id: "ph-002",
                category: "PETUGAS",
                fileName: "foto_petugas_rpt001.jpg",
                url: "/placeholder-petugas.jpg",
            },
        ],
        createdAt: "2026-03-07T15:30:00Z",
    },
    {
        id: "INC-002",
        reportId: "RPT-004",
        officerId: "u4",
        officerName: "Budi Prasetyo",
        kronologi:
            "Petugas melakukan kunjungan ke lokasi setelah menerima pengaduan. Korban ditemui di rumah bersama keluarga.",
        tindakan:
            "1. Wawancara dengan korban dan keluarga\n2. Dokumentasi kondisi\n3. Mengarahkan korban untuk melapor ke pihak berwajib",
        rekomendasi:
            "Memonitor situasi secara berkala dan memastikan keamanan korban.",
        photos: [
            {
                id: "ph-003",
                category: "LOKASI",
                fileName: "foto_lokasi_rpt004.jpg",
                url: "/placeholder-lokasi.jpg",
            },
        ],
        createdAt: "2026-03-06T10:00:00Z",
    },
];

